name: Setup Pact
description: Setup pact environment for running tests

inputs:
  version:
    description: "Target Pact version to install"
    required: false
    default: "4.10.0"

runs:
  using: composite
  steps:
    - name: Get pact binary
      shell: bash
      run: |
        mkdir bin
        cd bin
        wget https://github.com/kadena-io/pact/releases/download/v${{ inputs.version }}/pact-${{ inputs.version }}-linux-20.04.zip
        unzip "pact*.zip"
        chmod +x pact
        cd ..

    - name: Install z3 (ubuntu-18.04)
      uses: pavpanchekha/setup-z3@0.2.0
      with:
        version: "4.8.10"
        architecture: "x64"
        distribution: "ubuntu-18.04"
